1.What is NumPy?
    NumPy (Numerical Python) is a Python library used for working with arrays. It supports large, multi-dimensional arrays and matrices, along with a collection of mathematical functions.

2.What are the advantages of NumPy over Python lists?

Faster computation using vectorization.
Less memory usage.
Support for advanced mathematical functions and broadcasting.
Easy integration with C/C++ and other libraries like Pandas, SciPy.


In [2]:
!pip install numpy
import numpy as np
arr1 = np.array([1,2,3])

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 7.5 MB/s eta 0:00:0000:0100:01


In [3]:
arr1

array([1, 2, 3])

In [2]:

import numpy as np
zero_arry = np.zeros([3,4])
zero_arry
ones_arry = np.ones([100,2])
ones_arry


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.

In [12]:
zero_arry = np.zeros([12]).reshape(3,4)
zero_arry

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
import numpy as np
range_arry = np.arange(10,30,2.0).reshape(5,2)
range_arry


array([[10., 12.],
       [14., 16.],
       [18., 20.],
       [22., 24.],
       [26., 28.]])

In [16]:
lin_arry = np.linspace(0,5,10)
lin_arry.shape

(10,)

In [18]:
emp_arry = np.empty([2,4],dtype=int)
emp_arry

array([[104142712037065,               0,               0,
                      0],
       [              0,               0,               0,
                      0]])

In [25]:
eye_arry  = np.eye(3,4)# k is optional,+ve upper and -ve lower for 1 diagonal position
eye_arry

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [34]:
full_arry = np.full((2,2,3),[10,5,15])# with single value np.full((2,1),1)
full_arry

array([[[10,  5, 15],
        [10,  5, 15]],

       [[10,  5, 15],
        [10,  5, 15]]])

In [37]:
evne_arry = np.random.randint(50,101,(5,5))
evne_arry
evne_arry[evne_arry % 2 ==0] = 0
evne_arry

array([[87, 85, 61,  0, 99],
       [93, 53,  0, 81, 73],
       [95, 75,  0, 89, 59],
       [65, 81,  0, 61,  0],
       [ 0,  0,  0,  0, 93]])

In [51]:
np.random.seed(2)
print(np.random.rand(3))

[0.4359949  0.02592623 0.54966248]


In [47]:
print(np.random.rand(3))

[0.43532239 0.4203678  0.33033482]


Random cheat sheet
        | Function                                                 | Description                                            | Example                               |
| -------------------------------------------------------- | ------------------------------------------------------ | ------------------------------------- |
| `np.random.rand(d0, d1, ...)`                            | Random floats in \[0.0, 1.0)                           | `np.random.rand(3, 2)`                |
| `np.random.randn(d0, d1, ...)`                           | Random floats from normal distribution (mean=0, std=1) | `np.random.randn(2, 2)`               |
| `np.random.randint(low, high=None, size=..., dtype=int)` | Random integers                                        | `np.random.randint(1, 10, size=(3,))` |
| `np.random.choice(a, size=..., replace=...)`             | Random sample from array                               | `np.random.choice([1, 2, 3], size=2)` |
| `np.random.uniform(low, high, size=...)`                 | Uniform distribution                                   | `np.random.uniform(10, 20, 5)`        |
| `np.random.normal(loc, scale, size=...)`                 | Normal (Gaussian) distribution                         | `np.random.normal(0, 1, 5)`           |
| `np.random.shuffle(array)`                               | Shuffles an array **in-place**                         | `np.random.shuffle(arr)`              |
| `np.random.permutation(array)`                           | Returns a shuffled copy                                | `np.random.permutation(arr)`          |
| `np.random.seed(seed)`                                   | Set seed for reproducibility                           | `np.random.seed(42)`                  |
